name: I2T2

channels:
  - conda-forge

dependencies:
  - gdcm
  - pip
  - pip:
    - ipykernel==5.2.*
    - ipython==7.13.*
    - jupyter==1.0.*
    - jupyterlab==2.0.*
    - matplotlib==3.2.*
    - nbdev==0.2.*
    - numpy==1.18.*
    - pandas==1.0.*
    - pillow==7.1.*
    - pydicom==1.4.*
    - pypi==2.1
    - twine==3.1.*
