# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_dcm": "00_io.ipynb",
         "load_mat": "00_io.ipynb",
         "load_h5": "00_io.ipynb",
         "crop": "01_manipulate.ipynb",
         "pad": "01_manipulate.ipynb",
         "resample": "01_manipulate.ipynb",
         "resample_by": "01_manipulate.ipynb"}

modules = ["io.py",
           "manipulate.py"]

doc_url = "https://pfdamasceno.github.io/I2T2/"

git_url = "https://github.com/pfdamasceno/I2T2/tree/master/"

def custom_doc_links(name): return None
