# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"dcm2array": "00_data.manipulate.ipynb",
         "crop": "00_data.manipulate.ipynb",
         "pad": "00_data.manipulate.ipynb",
         "resample": "00_data.manipulate.ipynb",
         "resample_by": "00_data.manipulate.ipynb"}

modules = ["data/manipulate.py"]

doc_url = "https://UCSF-intelligent-imaging.github.io/I2T2/"

git_url = "https://github.com/UCSF-intelligent-imaging/I2T2/tree/master/"

def custom_doc_links(name): return None
