# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"dcm2array": "00_data.manipulate.ipynb"}

modules = ["data/manipulate.py"]

doc_url = "https://Pablo Damasceno.github.io/i2d2/"

git_url = "https://github.com/Pablo Damasceno/i2d2/tree/master/"

def custom_doc_links(name): return None
